# Generated by Django 5.1.3 on 2024-12-10 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Лекционный', 'Лекционный'), ('Мастерская', 'Мастерская'), ('Компьютерный', 'Компьютерный'), ('СЗ', 'СЗ'), ('ДО', 'ДО')], default='Лекционный', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prepods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Predmets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(to='testapp.group')),
                ('prepods', models.ManyToManyField(to='testapp.prepods')),
            ],
        ),
        migrations.CreateModel(
            name='PredGroupHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_total', models.IntegerField()),
                ('hours_used', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.group')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.predmets')),
            ],
        ),
        migrations.CreateModel(
            name='Raspis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота')], max_length=10)),
                ('num_pair', models.IntegerField()),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.cabs')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.group')),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.predmets')),
            ],
        ),
    ]
