# Generated by Django 5.1.3 on 2024-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabs',
            name='type',
            field=models.CharField(choices=[('Лекционный', 'Лекционный'), ('Компьютерный', 'Компьютерный')], default='Лекционный', max_length=50),
        ),
    ]
