# Generated by Django 5.1.3 on 2024-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_cabs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmets',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='predmets',
            name='prepods',
        ),
        migrations.CreateModel(
            name='Predgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(to='testapp.group')),
                ('name', models.ManyToManyField(to='testapp.predmets')),
                ('prepods', models.ManyToManyField(to='testapp.prepods')),
            ],
        ),
    ]
