# Generated by Django 5.1.3 on 2024-12-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_predmets_groups_remove_predmets_prepods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspis',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='PredPred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.ManyToManyField(to='testapp.predmets')),
                ('prepod', models.ManyToManyField(to='testapp.prepods')),
            ],
        ),
    ]
