# Generated by Django 5.1.3 on 2024-12-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_raspis_date_predpred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredPred',
        ),
    ]
