# Generated by Django 5.1.3 on 2024-12-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_delete_predpred'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='prepod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.prepods'),
        ),
    ]
