# Generated by Django 5.1.3 on 2024-12-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_predmets_prepod'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='need_cab',
            field=models.CharField(choices=[('Лекционный', 'Лекционный'), ('Компьютерный', 'Компьютерный')], default='Лекционный', max_length=50),
        ),
    ]
