# Generated by Django 5.1.3 on 2025-01-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_predmets_need_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmets',
            name='need_cab',
            field=models.CharField(blank=True, choices=[('Лекционный', 'Лекционный'), ('Компьютерный', 'Компьютерный')], default='Лекционный', max_length=50),
        ),
    ]
