# Generated by Django 5.1.3 on 2025-01-25 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_predmets_need_cab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predgrouphours',
            name='group',
        ),
        migrations.RemoveField(
            model_name='predgrouphours',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='raspis',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='raspis',
            name='group',
        ),
        migrations.RemoveField(
            model_name='raspis',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='cabs',
            name='type',
        ),
        migrations.RemoveField(
            model_name='predmets',
            name='need_cab',
        ),
        migrations.AddField(
            model_name='group',
            name='kurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kurator', to='testapp.prepods'),
        ),
        migrations.AddField(
            model_name='group',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='master', to='testapp.prepods'),
        ),
        migrations.AddField(
            model_name='predmets',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.cabs'),
        ),
        migrations.AddField(
            model_name='predmets',
            name='hours_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predmets',
            name='hours_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predmets',
            name='hours_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predmets',
            name='pairs_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prepods',
            name='predmet',
            field=models.ManyToManyField(blank=True, to='testapp.predmets'),
        ),
        migrations.RemoveField(
            model_name='predmets',
            name='prepod',
        ),
        migrations.DeleteModel(
            name='Predgroup',
        ),
        migrations.DeleteModel(
            name='PredGroupHours',
        ),
        migrations.DeleteModel(
            name='Raspis',
        ),
        migrations.AddField(
            model_name='predmets',
            name='prepod',
            field=models.ManyToManyField(blank=True, to='testapp.prepods'),
        ),
    ]
