# Generated by Django 5.1.3 on 2025-01-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_remove_predgrouphours_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='hours_1sem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='predmets',
            name='hours_2sem',
            field=models.IntegerField(default=0),
        ),
    ]
