# Generated by Django 5.1.3 on 2025-01-26 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_predmets_hours_1sem_predmets_hours_2sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmets',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.group'),
        ),
    ]
