# Generated by Django 5.1.3 on 2025-01-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_remove_predmets_prepod_predm_alter_predmets_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predm',
            name='prepod',
            field=models.ManyToManyField(blank=True, to='testapp.prepods'),
        ),
        migrations.AlterField(
            model_name='prepods',
            name='predmet',
            field=models.ManyToManyField(blank=True, to='testapp.predm'),
        ),
    ]
