# Generated by Django 5.1.3 on 2025-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_remove_predm_prepod'),
    ]

    operations = [
        migrations.AddField(
            model_name='predm',
            name='prepod',
            field=models.ManyToManyField(blank=True, to='testapp.prepods'),
        ),
    ]
