# Generated by Django 5.1.3 on 2025-01-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_predm_prepod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота')], max_length=2, verbose_name='День недели')),
                ('date', models.DateField(verbose_name='Дата')),
                ('pair_number', models.PositiveSmallIntegerField(verbose_name='Номер пары')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.cabs', verbose_name='Кабинет')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.predmets', verbose_name='Предмет')),
            ],
        ),
    ]
