# Generated by Django 5.1.3 on 2025-01-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='predm',
            name='ind',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='predmets',
            name='ind',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='index', to='testapp.predm'),
        ),
        migrations.AlterField(
            model_name='predmets',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_name', to='testapp.predm'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cabinet',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.cabs', verbose_name='Кабинет'),
        ),
    ]
