# Generated by Django 5.1.3 on 2025-02-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_predm_ind_predmets_ind_alter_predmets_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmets',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='prepods',
            name='Cab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.cabs'),
        ),
    ]
