# Generated by Django 5.1.3 on 2025-02-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_remove_predmets_cabinet_prepods_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.cabs', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testapp.predmets', verbose_name='Предмет'),
        ),
    ]
