# Generated by Django 5.1.3 on 2025-02-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0021_predmets_zachot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predmets",
            name="zachot",
            field=models.IntegerField(default=0),
        ),
    ]
