# Generated by Django 5.1.3 on 2025-02-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0022_alter_predmets_zachot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predmets",
            name="zachot",
        ),
    ]
